### ISSUE TITLE
Error Spammined

### ISSUE THREAD

**Issue by BenTheNoble** [drtshock/Factions#1084]
**FactionsUUID version (run `/f version`):** 
v1.6.9.5-U0.2.0-b46

**Server software (run `/version`):** 
PaperSpigot-"4c7641d" MC. 1.8.8

**Server (`logs/latest.log`):**

**Details:**
I keep getting this error spammed in console random times:
https://hastebin.com/bitivisayu.vbs

Also. /f perm doesnt work.
it doesnt open the gui

**Comment by LaxWasHere** [comment]
Please update to the latest build.

**Comment by drtshock** [comment]
There isn't a GUI in your build, which was stated in the release notes.

Please join our discord to verify your spigot name and get access to dev builds if you'd like to help us get this release out faster. If not, then just wait a few days for a  more stable release :)

Also, your issue is that we had a thing in that release that wasn't supported on 1.8, is fixed in dev builds.
