### ISSUE TITLE
/f perms bug

### ISSUE THREAD

**Issue by StefvanderMeer** [drtshock/Factions#1154]
FactionsUUID version (run `/f version`): 
You are running Factions v1.6.9.5-U0.2.2-b116

Server software (run `/version`): 
PaperSpigot 1.8.8

Server (`logs/latest.log`):
no errors found

Details:
I have set opening containers in claimed lands to true for enemies so people can raid easier. But with /f permissions the players can deny this and so have an advantage. I have disabled the command for now but could there please be a fix to this where you can deny them to change certain settings.

**Comment by CaptainMeoow** [comment]
f perms are pretty buggy for coleaders, this role is broken. 
It can not invite people, promote people, change titles, etc. It's not like I messed with the f perms, it's just broken. 

Also I have heard my community complaining about members being able to destroy f owner land, maybe put a small explanation for each f perm or a name to make clear what is would do example:"break owner land", etc. instead of using names that can not be understood by some less smart people.

**Comment by CmdrKittens** [comment]
Using #1217 to track this.
