### ISSUE TITLE
F Map Auto Update Bug

### ISSUE THREAD

**Issue by casey-johnson** [drtshock/Factions#1156]
FactionsUUID version (run `/f version`): 
V1.6.8.5-U0.2.2-b121
Server software (run `/version`): 
https://gyazo.com/4269aaa755c4b8b1ef7ffbe116d21807
Server (`logs/latest.log`):
https://pastebin.com/w9SeUvix
Details:
The F Map is not updating every chunk.
Screenshot of the relative config for f map is provided in the pastebin.
A video of the problem is also provided in the pastebin.
I did however find out while testing it with a friend, when the map was enabled to auto update, randomly 2 chunks would instantly update like it was supposed to. However, we could not replicate this happening, as it was random per-player what chunks on the map would choose to update instantly

Thanks for being such a responsive dev!!

**Comment by drtshock** [comment]
@dariasc didn't we see this before and fixed it?

**Comment by dariasc** [comment]
I can't recall although this does seem like a wierd issue

**Comment by CaptainMeoow** [comment]
When you fly the f map does not update when you walk it does, that's the issue and please try to fix it, as our community is complaining and it kinda kills finding bases.

**Comment by drtshock** [comment]
Ah so it's only an issue with flying? Because if so, should be an easy fix.

**Comment by dariasc** [comment]
Are we updating the map on the OnMove listener?

**Comment by drtshock** [comment]
Yes. Flying should be accounted for that too. Not sure why this would ever fail so we need more info.

**Comment by CaptainMeoow** [comment]
Yup, it's only broken when flying.
So when you do /f map on It should update each chunk you enter, it does when you walk so you walk walk walk reach the next chunk and you see a new updated
 f map appearing in chat, but if you use /fly it does not update. In our server a main way to find bases for donors is /fly /speed 10 /f map on, then they can fast check parts of our map for bases, ofc if it is broken, they have to walk and this takes a long time and causes a lot of complaining. It did work in the past, but since we got ourselves the newer version of the plugin it stopped working.

**Comment by CaptainMeoow** [comment]
Could you fix this please, it's really bothering us.

**Comment by CaptainMeoow** [comment]
Excuse me, but it takes kinda long

**Comment by VictorML11** [comment]
Actually I have just fixed it. The problem was in the FancyMessage send to the player.
We were checking if the player was at the ground. To be honest I do not know why.
Here is the PullRequest: #1163 

@drtshock  Should accept it. @CaptainMeoow I am sorry. I can not do an update you should wait, but it is already fixed.
If you can't wait much more I would suggest looking at my PullRequest changes and do it by yourself.

Have a nice day.

**Comment by dariasc** [comment]
#1166
