### ISSUE TITLE
/f perms Not Functioning Properly.

### ISSUE THREAD

**Issue by GranDaddySmoke** [drtshock/Factions#1210]
### FactionsUUID Version
You are running Factions v1.6.9.5-U0.3.0-b133

### Server Version
This server is running paper version git-paper-564 

### Logs
https://www.mediafire.com/file/ocy909ds8f1w8r9/latest.log/file

### Details
So my players have been complaining that /f perms isn't working so I went on to test it myself.
I allowed allys to my containers and no permission
I then just decided to allow every last thing available for new members-neutral (all categories) and yet still no ability to open chest or for example break ground on claimed land.

SO to finish up f perms doesn't actually work at all no matter what option or category.

**Comment by BboyZeroOne** [comment]
I can second that. Does not work on spigot 1.13.2 either. /perms GUI is misaligned for me too.

**Comment by GranDaddySmoke** [comment]
Posted 20 days ago and still no response for fix... lol

**Comment by CmdrKittens** [comment]
This is my next goal to fix. Things I plan to test and resolve as necessary, based on input in this issue:

* Chest opening (allies, new members)
* Breaking blocks (new members)

Anything else specifically that isn't working?

**Comment by CmdrKittens** [comment]
@BboyZeroOne Could you please create a separate issue on the GUI with some screenshot examples? I cannot reproduce that, but would love to work on it and don't want to mix that up with permission issues.

**Comment by CmdrKittens** [comment]
Chest opening is possible to control for faction members in territory. Could not reproduce any issues with that. However, allies/enemies definitely couldn't open stuff. This should be resolved as of https://github.com/drtshock/Factions/commit/cee0fa51b79c718ae6f587c99f8e3637485fac4b

For block breaking/placing, it was not possible to prevent faction members. This is now possible as of https://github.com/drtshock/Factions/commit/cee0fa51b79c718ae6f587c99f8e3637485fac4b

Please check out the latest build to see if it resolves your concerns. Leaving the issue open for at least a week to allow you to get back to me because this one's tricky, but if a week passes and I close it please feel free to respond here anyway! :)
