### ISSUE TITLE
/f perms Huge Load Issue

### ISSUE THREAD

**Issue by xxJinxedxx** [drtshock/Factions#1239]
### FactionsUUID Version
v1.6.9.5-U0.4.3-b170

### Server Version
PaperSpigot 1.8.8-R0.1-SNAPSHOT

### Logs
http://pasted.co/0588ed85

### Timings
https://timings.aikar.co/?id=82c60a76af1d47a9af158b1d3e72d35b#timings

### Details
There is a huge delay/load/response time when clicking the inventory with the f permissions.

**Comment by drtshock** [comment]
There are a lot of other plugins listening to our inventory clicks..

**Comment by xxJinxedxx** [comment]
Ok so if i get you right, that is from coming form FactionsUUID? I shouldn't be looking for anything external right?

**Comment by CmdrKittens** [comment]
Will investigate

**Comment by CmdrKittens** [comment]
In 0.5.0 (testing soon, then release), only the relevant perm icon updates. This is the least information processed and sent possible. Any further issues experienced on 0.5.0 and beyond should be reported in a separate ticket.

**Comment by CmdrKittens** [comment]
After some helpful testing, we were able to narrow this down to MVdWPlaceholderAPI causing horrible lag when it encountered an unknown placeholder, which existed because we had our own little placeholder-like content in the message being sent to MVdWPlaceholderAPI. Each call to MVdWPlaceholderAPI took more than one tick, and there were dozens of them. While technically a bug in MVdWPlaceholderAPI, we've resolved it for the 0.5.0 release and extensively tested it to confirm.
