### ISSUE TITLE
Classes moved of package

### ISSUE THREAD

**Issue by daniel097541** [drtshock/Factions#1304]
### FactionsUUID Version
Factions v1.6.9.5-U0.5.2-b198

### Server Version
Taco 1.8.8

### Logs
Caused by: java.lang.NoSuchMethodError: com.massivecraft.factions.FPlayer.getRole()Lcom/massivecraft/factions/struct/Role;

### Details
Hi, im the developer of beastcore, i have a hook to your plugin for some features.
In latest version of the plugin (or some before) you seemed to move some classes of package, (Role or Relation) this has broken the compatibility with other versions of your plugin, also it wont be possible having a hook shared with other forks of factionsUUID.
Could you move back those classes to their previous packages?
Thanks, have a nice day

**Comment by CmdrKittens** [comment]
Howdy! I appreciate your reaching out to us.

With the 0.5.0 release, we reshuffled a bunch of code around all at once to ensure breakages wouldn't be a regular thing but a rare event. Part of this reshuffle involved a few sanity-related refactors around package names. Completely murdered the entire zcore package, for example. 

For any open-source plugins brought to us, we have worked directly with authors (including providing code via pull request) to help them support these changes. I'm willing to give you tips on how to easily detect when you're dealing with FactionsUUID to make your hopefully simple modifications pretty straightforward:

1) You can detect FactionsUUID from its version. [Click here](https://github.com/drtshock/Factions#versioning) for details on that. With 0.5.0 we continue to support everything from 1.8.8 through 1.14.4, so if you detect FactionsUUID you can safely start using the newer code calls because they should be up to date (0.5.0 has been out for a month now)
2) You could just do detection by trying `Class.forName()` on the old `struct` location and pulling up the FactionsUUID code instead in the event it's not present.

If you have any other questions please feel free to respond here. You can also get some help from folks on our [Discord](https://discord.gg/PHpuzZS) 😸

**Comment by CmdrKittens** [comment]
@daniel097541 Giving you a friendly username ping in case you missed the above reply before. Hope you found a viable solution! :)

**Comment by CmdrKittens** [comment]
At almost a month, I'm closing this. Totally fine with continuing conversation regardless, but I like to remove handled concerns so I stop looking at them and saying "wait, what should I do about this?"
