### ISSUE TITLE
[BUG] Conflict issue with EssentialsXChat

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#1407]
### Debug info
*https://imgur.com/a/yh2IS8N* 

### Details
*I use the chat radius feature on EssentialsXChat, with a money cost set for each message you decide to shout on chat. The problem starts whenever I install this plugin, so the messages that you decide to shout will always shout even if you don't have the required amount of money. The weird thing is that absolutely nothing displays on the console, not even the message you shouted.*

*On the link below, there is an image showing a message I shouted on chat, without having the required amount of money for shouting a message, and I do get the message that "you don't have enough funds", but the message still gets sent:*
https://i.imgur.com/vagbYtj.png

I figured this out on an empty localhost only using these plugins:
- Factions-b239
- EssentialsX-2.18.1.0
- EssentialsXChat-2.18.1.0
- Vault
- Luckperms 

**Steps to reproduce it:**
1- Make sure to install all those 5 plugins.

2- Once you load them, set the "radius" option on the essentials config to any value above 0 so you enable the chat-radius feature.

3- On the "command-costs" sections of the Essentials config, set a random money cost for the command "`chat-shout`".

4- Give the default group, permission to use the shout command with `/lp group default permission set essentials.chat.shout`

5- Make sure your balance is below to the one you set on the commandcost for shouting a message, and then just shout any message in the chat, for example: "`!Hello`". You will see that the "not enough funds" will appear, but your shouted message will still get sent.

Thanks in advance for reading!

**Comment by dariasc** [comment]
I was able to confirm this issue. A temporary fix until I figure out exactly what is happening is to set `factions.chat.tagHandledByAnotherPlugin` to true in the config.

**Comment by dariasc** [comment]
So I've narrowed the issue down. Essentials seems to cancel the chat event with the `HIGHEST` priority [here](https://github.com/EssentialsX/Essentials/blob/6e6dd041d50c1e2b84c7dac2e43ea5accdb2b631/EssentialsChat/src/com/earth2me/essentials/chat/EssentialsChatPlayerListenerHighest.java#L25).

Now our tag handling also happens in at `HIGHEST` priority, this wouldn't be an issue but because we have relational colors the message is sent individually to all recipients [here](https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/listeners/FactionsChatListener.java#L165), this means when Essentials cancels the message it has already been sent individually to everyone. As a solution we could just jump up a priority to `MONITOR` so we can check if it was cancelled but `MONITOR` isn't supposed to modify the event in any way.

At this point I think the fix is to just to enable the config option if you want to use that essentials feature.

Would love your insight @CmdrKittens.

**Comment by ghost** [comment]
Thanks a lot for explaining and narrowing up this issue @Dariasc !
And indeed, the only way to fix it for now would be by enabling that option. Though I prefer to stay with the option disabled since I find it impossible to handle and insert the factions placeholders into the Essentials chat these last days. The ChatInyector is unsupported and abandoned, and it doesn't work with the last PlaceholderAPI version, concluding in lot of visual errors on the placeholders.
So for now I'm going to stay with that option disabled, and wait until there are some news in here. Otherwise I will have to look for another Chat plugin that includes all the features that I used on EssentialsXChat and also supports Placeholders on it.

**Comment by mbax** [comment]
> I was able to confirm this issue. A temporary fix until I figure out exactly what is happening is to set `factions.chat.tagHandledByAnotherPlugin` to true in the config.

Can confirm, this *is* the option. Factions handles chat in a particular way and that's incompatible with the distance-based chatting.

I think Carbon can do what you're looking for - https://github.com/Hexaoxide/Carbon/wiki/Basic-Configuration
