### ISSUE TITLE
/f access

### ISSUE THREAD

**Issue by thomasb454** [drtshock/Factions#146]
Hi,

The /f access command I feel would be a great addition to the Factions plugin -- and for many servers is needed.

Syntax:

/f access p [player name]
/f access f [faction name]

This will allow players from OTHER Factions to be able to build there (basically like being a Faction member, but only have access in that area)

**Comment by drtshock** [comment]
I can see this being useful for other Factions, but why for your own faction?

**Comment by thomasb454** [comment]
Huh?

You'd type /f access p [player] -- so other players from OTHER factions could build there.

**Comment by drtshock** [comment]
Justification:
"To build in your alt faction's land. Also, if you have allies with whom you share a base, or farm with. Also, during an event such as a cannon raid, you might want your allies helping you build the cannon."

I'll look at adding this once I'm able to pull downstream changes to update f show in the next day or two :)

**Comment by SlayerMarth** [comment]
I wasn't sure if I was to make a new one or just add my two cents to this one. Figured adding it here rather than making a new "issue" with the same info makes more sense. 

Piggy backing off what Thomas was saying, yes it can be used to give other people/factions access to your claims. Makes it so close allies or people you trust who aren't in your faction help you with your building and such. But the main use that it served before it was removed was the fact that you could invite random people to your faction to use for power, but you deny access for them building in your trusted members chunks. 

ie. Claiming 5 chunks like

xx
xx    o

x being the trusted claims where your veteran members can build their vaults and such, while o being the claims where new members can build but they don't have access to touch the trusted claims.

Nonetheless, I **+1** this when you can. :) My apologies if I've typed to much here unnecessarily.

**Comment by mbax** [comment]
Covered by upcoming zones feature. Redirecting issue to #1437
