### ISSUE TITLE
Factions still causing lag spikes

### ISSUE THREAD

**Issue by iaxedu** [drtshock/Factions#197]
As reaction on issue #193 

These timings are with the latest build: http://timings.aikar.co/?url=9645432

Still lag spikes

**Comment by Kakifrucht** [comment]
Yeah, this is really annoying.
The tooltips are the feature that started the whole lagg on /f who commands and stuff. I would rather have it removed until it all works fine.

**Comment by CullanP** [comment]
It seems I'm having an even worse issue. I just noticed that every player online is showing up in f who http://puu.sh/dYr8f/d2e4ae4ca9.png. I am still forced to use my old f who class so the lag is subsided. I'm curious to know what's causing every player on the server to show up in /f who for me. the instant someone on my server uses /f who, the server crashes with lag, I think this is because of all of the offline players it is grabbing.

**Comment by iaxedu** [comment]
New timings server unstable: http://timings.aikar.co/?url=9660511

**Comment by drtshock** [comment]
Will be fixed in that commit. I just removed the tooltips from that entirely.

**Comment by Kakifrucht** [comment]
Thanks man, any chance they will be coming back without causing performance issues?

**Comment by drtshock** [comment]
Possibly. I guess @t00thpick1 was working on a solution for this.

**Comment by CullanP** [comment]
I think there's something else underlying in this issue, not tool-tips, If tool-tips were to blame, my /f list would lag on use, it doesn't. As my screenshot shows; every player  online/offline is coming up in my f who. I was forced to use the old f who class in order to have a non-laggy f who class. When I did debug this awhile ago I seen the issue was coming from this line in cmdshow.java "for (FPlayer p : MiscUtil.rankOrder(faction.getFPlayers())) {". I know it's this line because when I put debug messages before and after it the messages stop at that line. I believe the issue to be in FPlayer, not sure what, but whatever is causing this issue if fixed would more then likely not only be a performance difference for cmdshow, but also other things using FPlayer as a variable

**Comment by Kakifrucht** [comment]
The lagg was clearly coming from the lookups...
Don't use a modified Factions and then come into the bug tracker to report your issues.
Your issue is something else.

**Comment by CullanP** [comment]
If I exactly copy the cmdshow.java class, it lags. It's the exact same methods being used, don't tell me what's modified and what's not.

**Comment by Kakifrucht** [comment]
I can tell you that issues like the ones you are telling us about never existed before and the laggs that are being talked about in this thread come from the tooltips, as the tooltips were the first build that introduced that lag. drtshock even confirmed that. No reason for negative attitude.

**Comment by CullanP** [comment]
Would you like to come on my server and tell me tooltips are causing lag? Because I'm pretty sure we handle 100+ players with 20 tps with no lag, I kept /f list and removed/updated /f show, no lag issues now whatsoever. Only issue I have with this plugin, is f show, and I've even said the line it gets stuck on. I'm not being negative, I'm just a bit insulted that you would say it's my "modified" version's fault. In-fact, I haven't touched FPlayer or MiscUtil class until I had to
