### ISSUE TITLE
Portals are created in claimed land

### ISSUE THREAD

**Issue by cnr** [drtshock/Factions#204]
`<Thomastremix307> Hello is it possible to stop netherportals spawning in claimed areas ?`

Not sure which label(s) to use for this ("bug", "enhancement", or both), but it's something we should probably resolve sooner than later.

**Comment by drtshock** [comment]
This would have to be set for all claimed land though because I don't believe theres a way to track who created a portal.

**Comment by Tibowl** [comment]
Won't EntityCreatePortalEvent work?
Check all blocks, if in land: check if entity is a player if not, deny, if so check faction of that player if he can build  (maybe same method as block breaking, placing, etc) if so allow else deny.

Maybe instead of stopping the portal, move it outside the claim?

**Comment by Tibowl** [comment]
Can't edit on mob, but I just saw that that event only gets called when ender Dragon dies. Maybe PlayerPortalEvent, check if destination exists else check stuff?

**Comment by drtshock** [comment]
Added :)
