### ISSUE TITLE
DTR Freeze

### ISSUE THREAD

**Issue by SnakeDaoust1232** [drtshock/Factions#229]
When a member of a faction dies, the faction should have to wait an hour before they can regen power
the countdown should reset if another faction member dies. For Example: if you have been waiting 30 minutes for the dtr freeze and one of your members dies, the countdown goes back up to 60 minutes.

The time should be configurable in the config.yml :P

The DTR Freeze should be counting down in the f show also. 

EX: "DTR Freeze: 30 Minutes 15 Seconds"

**Comment by MoeXIV** [comment]
I've had issues with that too. The f show is somewhat bugged as well. On my development server, my DTR goes up by 1, not 0.1, and is currently at 9 instead of maxing at 5.5.

These are the first available builds, so it's a lot to ask for. But I do agree, DTR Freeze is a must have for any HCF server. Including BasicHCF :)

**Comment by drtshock** [comment]
@MoeXIV can you make a separate issue for any issues you have with DTR?

I'll go ahead and add this.
