### ISSUE TITLE
Need Help with configuring DTR

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/Factions#260]
I'm not agreeing to the part "HCF Portion doesn't work", but I am having significant troubles trying to make the DTR work for me. Everyone just says edit the power, but it still doesn't show decimal places, doesn't go negative, you can only have 5 claims, (Due to max power having to be 5 for the faction), and there's just a lot more.

Any help with making this work would be great.

**Comment by nscwalk** [comment]
Moe There is a temporary option here ,but I would like to add that It would be nice that he can make it so when you enable dtr that will not put a maximum on your amount of land per claim with power. but as a temporary solution you can do this. Set players power to 55 set power loss per death to 100 then set maximum power to 550. then you set your maximum land claim to 36. this is all done in the regular factions config file. the idea is everyone instead of having 5.5 dtr its 55 ,but instead of losing 1 dtr they lose 100. so bassicly it would look like this Max dtr is 550 And since each player loses 100 per death it would work the same way while being able to claim 36 land claims because you have 550 land. you will also have to disable overclaiming in the config to. but I would like to agree with you they should make it so when you enable "DTR"/"HCF" Feature in the config. they disable how much land you can claim per power and just have a set maximum claim you can set in the config.

**Comment by drtshock** [comment]
DTR will be added in a separate project. I'll post all the details on spigot and twitter soon.
